### ISSUE TITLE
Guide

### ISSUE THREAD

**Issue by linkage87** [EasyFarm/EasyFarm#229]
any guide on how to get this set up never used a program like this before i tried to set it up and when i check the log it says its running and says that it is targeting the mob i selected but on ffxi its doing nothing ;/

**Comment by Mykezero** [comment]
The [wiki](https://github.com/EasyFarm/EasyFarm/wiki) contains some information, but the user interface has change quite a bit since it was written. There are some [YouTube](https://www.youtube.com/playlist?list=PLwWkdiOAlVMbUs7hQLZ05BOpoOLAyffmx) videos as well, but not many of them

Very strange that the program would say it's targeting something but do nothing since the program should work as a melee bot even when un-configured.

**Comment by linkage87** [comment]
I tried making a route today to see if that would work and didn't move at all after hitting start did I miss something when setting up all I did was install try to configure it and hit start I hear tonsvof good things about it but sucks idk what I'm doing wrong

**Comment by Mykezero** [comment]
@linkage87 I've added extra logging to the program. Mind downloading the newest version and running it again with no settings? Make sure you are within 5 yalms of the mob please. 

If there's a problem it should be logged in the Log tab. You should see something like this: 

![image](https://cloud.githubusercontent.com/assets/5349608/21752877/5cfaf2bc-d5ae-11e6-9e59-6098a382d452.png)

The details will be included in the Logs/easyfarm.log file, The log file will kind of look like this (the message will be different): 

**easyfarm.log**
```
2017-01-08 14:23:34.4021|INFO|LogSink|EasyFarm Started ...
2017-01-08 14:23:53.3843|ERROR|LogSink|FSM error
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.CancellationToken.ThrowIfCancellationRequested()
   at EasyFarm.States.FiniteStateMachine.RunStateMachine() in C:\Users\mike\Documents\GitHub\EasyFarm\EasyFarm\States\FiniteStateMachine.cs:line 119
   at EasyFarm.States.FiniteStateMachine.<RunFiniteStateMainWithThread>b__8_0() in C:\Users\mike\Documents\GitHub\EasyFarm\EasyFarm\States\FiniteStateMachine.cs:line 94
```

Hopefully that will tell us why the program isn't taking any actions.

**Comment by Mykezero** [comment]
@Linkage87 Is this working for you now? This was quite a few updates ago.

**Comment by kromalogo** [comment]
2017-05-28 20:09:13.1933|INFO|LogSink|EasyFarm Started ...
2017-05-28 20:09:33.6093|ERROR|LogSink|FSM error
System.Exception: No key Trusts in battle lists to get value. 
   en EasyFarm.Classes.BattleLists.get_Item(String index) en C:\projects\easyfarm\EasyFarm\Classes\BattleLists.cs:línea 62
   en EasyFarm.States.SummonTrustsState.Check() en C:\projects\easyfarm\EasyFarm\States\SummonTrustsState.cs:línea 129
   en EasyFarm.States.FiniteStateMachine.RunStateMachine() en C:\projects\easyfarm\EasyFarm\States\FiniteStateMachine.cs:línea 150
   en EasyFarm.States.FiniteStateMachine.<RunFiniteStateMainWithThread>b__9_0() en C:\projects\easyfarm\EasyFarm\States\FiniteStateMachine.cs:línea 99

**Comment by amblybiguity** [comment]
I keep getting error with this in log:

2018-01-13 10:05:44.3410|ERROR|LogSink|FSM error
System.NullReferenceException: Object reference not set to an instance of an object.
   at EasyFarm.States.MenuState.GetMenuCommands() in C:\projects\easyfarm-j97ja\EasyFarm\States\MenuState.cs:line 57
   at EasyFarm.States.MenuState.Check() in C:\projects\easyfarm-j97ja\EasyFarm\States\MenuState.cs:line 24
   at EasyFarm.States.FiniteStateMachine.RunStateMachine() in C:\projects\easyfarm-j97ja\EasyFarm\States\FiniteStateMachine.cs:line 151
   at EasyFarm.States.FiniteStateMachine.<RunFiniteStateMainWithThread>b__9_0() in C:\projects\easyfarm-j97ja\EasyFarm\States\FiniteStateMachine.cs:line 100

I did not install Easyfarm into this path. I was getting similar erros, i saw the log file refer to this path so I tried copying the easyfarm folder into this c:\projects\easyfarm-j97ja\ path and it gives this error instead.

shouldn't any path references be related to the current context? how should this be fixed?

**Comment by Mykezero** [comment]
@amblybiguity Ticket #311 has been created for this. I'd need to research to see if there's a work around currently available.

**Comment by kamakaz** [comment]
I for the life of me can not figure out how to open this apparently I'm stupid lol. I'm not seeing a .exe. Is there a tutorial on how to open it or am I supposed to put the files in a specific place?

**Comment by Mykezero** [comment]
Hi @kamakaz, maybe you downloaded the source files instead of the application?

Here's a link to the exe file to run EasyFarm: 
* https://github.com/EasyFarm/EasyFarm/releases/download/EasyFarm-1.0.125/EasyFarm.zip

**Comment by danmansyx9** [comment]
Was working fine until yesterday. When click start it does as normal except it won’t cast trusts. I disable trust then click start again it will find monster and do ad it should but then it won’t loop to next one. Only way to get it to work is by pausing and starting again.

**Comment by palookaville** [comment]
I have the exact same issue as OP. Have latest version from above link, but in game no response other than to move into 1st person and rotate around?

**Comment by palookaville** [comment]
I got this in the latest log.txt:
2018-06-17 17:11:15.5377 EasyFarm.Logging.NLogTextFileLogger FSM thread interrupted
System.Threading.ThreadInterruptedException: Thread was interrupted from a waiting state.
   at System.Threading.Thread.SleepInternal(Int32 millisecondsTimeout)
   at System.Threading.Thread.Sleep(Int32 millisecondsTimeout)
   at EasyFarm.Classes.Player.SetTargetByTabbing(IMemoryAPI fface, IUnit target) in C:\projects\easyfarm\EasyFarm\Classes\Player.cs:line 116
   at EasyFarm.Classes.Player.SetTarget(IMemoryAPI fface, IUnit target) in C:\projects\easyfarm\EasyFarm\Classes\Player.cs:line 99
   at EasyFarm.States.ApproachState.Run() in C:\projects\easyfarm\EasyFarm\States\ApproachState.cs:line 73
   at EasyFarm.States.FiniteStateMachine.RunStateMachine() in C:\projects\easyfarm\EasyFarm\States\FiniteStateMachine.cs:line 156
   at EasyFarm.States.FiniteStateMachine.<RunFiniteStateMainWithThread>b__9_0() in C:\projects\easyfarm\EasyFarm\States\FiniteStateMachine.cs:line 98

**Comment by Lion0102** [comment]
Hi @Mykezero I know this issue was a while ago, but I was wondering if you're still active and willing to help out a little? I would gladly even pay you a little compensation for fixing my own issue with the bot.

The bot runs for like 5-30 mins before an error occurs and the bot stops.

Here's the logs.

2019-11-15 20:51:23.0736 EasyFarm.Logging.NLogTextFileLogger EasyFarm Started ...
2019-11-15 21:37:16.0182 EasyFarm.Logging.NLogTextFileLogger FSM error
System.InvalidOperationException: Kokoelmaa muutettiin luetteloinnin aloittamisen jälkeen.
   kohteessa System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   kohteessa System.Collections.Generic.Queue`1.Enumerator.MoveNext()
   kohteessa System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   kohteessa System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   kohteessa EasyFarm.States.BattleState.ShouldRecycleBattleStateCheck() tiedostossa C:\projects\easyfarm\EasyFarm\States\BattleState.cs:rivillä 81
   kohteessa EasyFarm.States.BattleState.Run() tiedostossa C:\projects\easyfarm\EasyFarm\States\BattleState.cs:rivillä 70
   kohteessa EasyFarm.States.FiniteStateMachine.RunStateMachine() tiedostossa C:\projects\easyfarm\EasyFarm\States\FiniteStateMachine.cs:rivillä 171
   kohteessa EasyFarm.States.FiniteStateMachine.<RunFiniteStateMainWithThread>b__9_0() tiedostossa C:\projects\easyfarm\EasyFarm\States\FiniteStateMachine.cs:rivillä 99

Any idea how to fix this? I've downloaded the recent source file.

**Comment by Pantafernando** [comment]
Im having the same problem (i guess cant understand your language but translator said its the same).

I found this link, maybe can fix, dont hurt to try. Gonna do this on my game.

https://github.com/EasyFarm/EasyFarm/issues/417

**Comment by Lion0102** [comment]
Oh thanks a lot, I'll check that version when I get home. Cheers.
