### ISSUE TITLE
EliteAPI.DLL Unable to Load

### ISSUE THREAD

**Issue by shadow9555** [EasyFarm/EasyFarm#230]
I am pretty sure this is not a EasyFarm but i am completely lost because i have tried everything i know. and its only happening on this one laptop.

when selecting the character name i get  Unable to load dll 'EliteAPI.dll': the specified module could not be found 0x8007007E

1. All C++ libs are install 
2. EliteAPI.DLL does exists in the Easy Farm Directory
3. i have tried re downloading the latest build.
4. i have uninstalled and reinstall all the C++ Librarys
5. program is run as administrator

It feels like windows is broken somehow. My only solution is to reinstall windows which i rather avoid i am hopping someone out there has seen this and can point me in the right direction. 

I have attach a screen shoot of what going on and you can see i pass the EliteMMO checker

![ffxi](https://cloud.githubusercontent.com/assets/16257464/21664151/66adc610-d2aa-11e6-8080-afec8bdc1522.png)

**Comment by Mykezero** [comment]
Have you tried installing [Microsoft .NET Framework 4.5](https://www.microsoft.com/en-US/Download/details.aspx?id=30653)? 

You shouldn't need to do a re-install: the software should work as is, as long as all required files are in place. The re-install wouldn't do anything to make the program work. 

Hopefully that's the only thing left that's missing, and it seems you have the rest installed.

**Comment by shadow9555** [comment]
i had hope that was it because i realize that the EliteMMOcheck only tested up to 4.0 but i had confirmed it has .net 4.5 and i have ran a repair on it and still having the same issue

**Comment by Mykezero** [comment]
I've added logging to the newest version. Would you mind try using that version? The logs/easyfarm.log file might contain a description of what's exactly going on.

**Comment by JoshTyree90** [comment]
I'm having this issue on one of my Windows 10 computers. My other Win 10 computer runs this program just fine however. I'm not sure what the difference is, they're all using the same image haha.

2017-03-07 12:50:55.6884|INFO|LogSink|EasyFarm Started ...
2017-03-07 12:51:01.0441|FATAL|LogSink|Unhandled Exception
System.DllNotFoundException: Unable to load DLL 'EliteAPI.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at EliteMMO.API.EliteAPI.CreateInstance(Int32 processId)
   at MemoryAPI.EliteMMOWrapper..ctor(Int32 pid) in C:\projects\easyfarm\MemoryAPI\Memory\EliteMMOWrapper.cs:line 25
   at EasyFarm.ViewModels.MasterViewModel.SelectProcess() in C:\projects\easyfarm\EasyFarm\ViewModels\MasterViewModel.cs:line 250
   at Prism.Commands.DelegateCommand.<>c__DisplayClass1_0.<.ctor>b__0(Object o)
   at Prism.Commands.DelegateCommandBase.<>c__DisplayClass5_0.<.ctor>b__0(Object arg)
   at Prism.Commands.DelegateCommandBase.<Execute>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Prism.Commands.DelegateCommandBase.<System-Windows-Input-ICommand-Execute>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Davepill** [comment]
Bump, have the same issue on a laptop as well. Anyone found what cause the problem?

**Comment by iisoloii** [comment]
Anyone find a fix for this i'm having the same issue, works perfect on my windows 10 pc and doesnt work on my windows 7?

**Comment by Mykezero** [comment]
These instructions may be able to help on Windows 7:
* https://github.com/EasyFarm/EasyFarm/issues#issuecomment-391574392

Please let me know if this helps!
