### ISSUE TITLE
error after selecting character

### ISSUE THREAD

**Issue by afkplay** [EasyFarm/EasyFarm#284]
Hello,
after i select my character i get this error:
An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)

checked elitemmo system checker and i got everything installed.

here is the log for the error:
2017-08-07 18:16:14.5836|INFO|LogSink|EasyFarm Started ...
2017-08-07 18:16:26.6264|FATAL|LogSink|Unhandled Exception
System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at EliteMMO.API.EliteAPI.CreateInstance(Int32 processId)
   at MemoryAPI.EliteMMOWrapper..ctor(Int32 pid) in C:\projects\easyfarm\MemoryAPI\Memory\EliteMMOWrapper.cs:line 25
   at EasyFarm.ViewModels.MasterViewModel.SelectProcess() in C:\projects\easyfarm\EasyFarm\ViewModels\MasterViewModel.cs:line 251
   at Prism.Commands.DelegateCommand.<>c__DisplayClass1_0.<.ctor>b__0(Object o)
   at Prism.Commands.DelegateCommandBase.<>c__DisplayClass5_0.<.ctor>b__0(Object arg)
   at Prism.Commands.DelegateCommandBase.<Execute>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Prism.Commands.DelegateCommandBase.<System-Windows-Input-ICommand-Execute>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by afkplay** [comment]
problem was solved after re-installing visual studio c++ 2015

**Comment by Mykezero** [comment]
Thanks, @afkplay, I'm glad you were able to figure this out!
