### ISSUE TITLE
Battle tab > Start broken?

### ISSUE THREAD

**Issue by mbout4it** [EasyFarm/EasyFarm#297]
Under the "Start" when I add in Sneak Attack, the bot seems to just stand still and not do anything.  If I stop it and uncheck Sneak Attack on the start, it works normally.  is this a bug or broken?  I think I gotten it to work before.

**Comment by mbout4it** [comment]
Here's the log

2017-12-06 18:34:50.6465|INFO|LogSink|FSM thread interrupted
System.Threading.ThreadInterruptedException: Thread was interrupted from a waiting state.
   at System.Threading.Thread.SleepInternal(Int32 millisecondsTimeout)
   at System.Threading.Thread.Sleep(Int32 millisecondsTimeout)
   at EasyFarm.Classes.Executor.MonitorCast() in C:\projects\easyfarm\EasyFarm\Classes\Executor.cs:line 175
   at EasyFarm.Classes.Executor.UseBuffingActions(IEnumerable`1 actions) in C:\projects\easyfarm\EasyFarm\Classes\Executor.cs:line 74
   at EasyFarm.States.StartState.Run() in C:\projects\easyfarm\EasyFarm\States\StartState.cs:line 55
   at EasyFarm.States.FiniteStateMachine.RunStateMachine() in C:\projects\easyfarm\EasyFarm\States\FiniteStateMachine.cs:line 163
   at EasyFarm.States.FiniteStateMachine.<RunFiniteStateMainWithThread>b__9_0() in C:\projects\easyfarm\EasyFarm\States\FiniteStateMachine.cs:line 99

**Comment by mbout4it** [comment]
Here's the log from the latest release

2017-12-06 18:29:50.9368|ERROR|LogSink|FSM error
System.NullReferenceException: Object reference not set to an instance of an object.
   at EasyFarm.States.MenuState.GetMenuCommands() in C:\projects\easyfarm-j97ja\EasyFarm\States\MenuState.cs:line 57
   at EasyFarm.States.MenuState.Check() in C:\projects\easyfarm-j97ja\EasyFarm\States\MenuState.cs:line 24
   at EasyFarm.States.FiniteStateMachine.RunStateMachine() in C:\projects\easyfarm-j97ja\EasyFarm\States\FiniteStateMachine.cs:line 151
   at EasyFarm.States.FiniteStateMachine.<RunFiniteStateMainWithThread>b__9_0() in C:\projects\easyfarm-j97ja\EasyFarm\States\FiniteStateMachine.cs:line 100

**Comment by mbout4it** [comment]
I got it working but not in the START but on PULL function.
