### ISSUE TITLE
Follow - Runs to first point then stops

### ISSUE THREAD

**Issue by WillGSX** [EasyFarm/EasyFarm#306]
Hello,

My issue is when I try to enable following; when I start the program it will run to the target I give at that specified distance, but then it will no longer follow from there.

**Comment by Altalus** [comment]
I confirm the behavior.

In my case it might be because this happens (in the logs):

```
2018-01-06 13:16:51.1817|INFO|LogSink|EasyFarm Started ...
2018-01-06 13:17:46.8417|ERROR|LogSink|FSM error
System.NullReferenceException: Object reference not set to an instance of an object.
   at EasyFarm.States.MenuState.GetMenuCommands() in C:\projects\easyfarm-j97ja\EasyFarm\States\MenuState.cs:line 57
   at EasyFarm.States.MenuState.Check() in C:\projects\easyfarm-j97ja\EasyFarm\States\MenuState.cs:line 24
   at EasyFarm.States.FiniteStateMachine.RunStateMachine() in C:\projects\easyfarm-j97ja\EasyFarm\States\FiniteStateMachine.cs:line 151
   at EasyFarm.States.FiniteStateMachine.<RunFiniteStateMainWithThread>b__9_0() in C:\projects\easyfarm-j97ja\EasyFarm\States\FiniteStateMachine.cs:line 100
```

New file, only changed the Follow to target my 1st player.

**Comment by Altalus** [comment]
@WillGSX I was able to make it work by adding `Testing` to the `Menu` tab (and pressing save, of course).

I guess the program right now actually expect this box to have something, anything.

Wiki does not explains what the box does however ;)

**Comment by Altalus** [comment]
@WillGSX I spoke too fast. I also had to remove any abilities in the `Healing` section.
