### ISSUE TITLE
Program running, Targets mob but nothing happens. 

### ISSUE THREAD

**Issue by Specwarrior** [EasyFarm/EasyFarm#323]
I’m sorry if this is answered somewhere else, I’ve looked but couldn’t find a resolution. I’ve done what I think is required to get easy farm going, I’ve selected my character, started program, it targets mob...but that’s where it ends, I have tried so many things in the menu but nothing will start the bot from attacking. Please help!! I’d also like to apologize in advance, I’m very computer illiterate.

**Comment by NotNickerz** [comment]
I am having the same issue with this - It started when I reinstalled windower- It attempt to target a monster but it just stands still - Log doesnt show any errors - log shows this -  

2018-04-06 21:25:15.6329|INFO|LogSink|EasyFarm Started ...
2018-04-06 21:26:12.1631|INFO|LogSink|FSM thread interrupted
System.Threading.ThreadInterruptedException: Thread was interrupted from a waiting state.
   at System.Threading.Thread.SleepInternal(Int32 millisecondsTimeout)
   at System.Threading.Thread.Sleep(Int32 millisecondsTimeout)
   at EasyFarm.Classes.Executor.EnsureCast(String command) in C:\projects\easyfarm\EasyFarm\Classes\Executor.cs:line 150
   at EasyFarm.Classes.Executor.UseBuffingActions(IEnumerable`1 actions) in C:\projects\easyfarm\EasyFarm\Classes\Executor.cs:line 74
   at EasyFarm.States.EndState.Run() in C:\projects\easyfarm\EasyFarm\States\EndState.cs:line 64
   at EasyFarm.States.FiniteStateMachine.RunStateMachine() in C:\projects\easyfarm\EasyFarm\States\FiniteStateMachine.cs:line 156
   at EasyFarm.States.FiniteStateMachine.<RunFiniteStateMainWithThread>b__9_0() in C:\projects\easyfarm\EasyFarm\States\FiniteStateMachine.cs:line 98
2018-04-06 21:26:30.2302|INFO|LogSink|FSM thread interrupted
System.Threading.ThreadInterruptedException: Thread was interrupted from a waiting state.
   at System.Threading.Thread.SleepInternal(Int32 millisecondsTimeout)
   at System.Threading.Thread.Sleep(Int32 millisecondsTimeout)
   at MemoryAPI.Memory.EliteMmoWrapper.NavigationTools.MoveForwardTowardsPosition(Func`1 targetPosition, Boolean useObjectAvoidance) in C:\projects\easyfarm\MemoryAPI\Memory\EliteMMOWrapper.cs:line 124
   at MemoryAPI.Memory.EliteMmoWrapper.NavigationTools.GotoNPC(Int32 id, Boolean useObjectAvoidance) in C:\projects\easyfarm\MemoryAPI\Memory\EliteMMOWrapper.cs:line 97
   at EasyFarm.States.ApproachState.Run() in C:\projects\easyfarm\EasyFarm\States\ApproachState.cs:line 66
   at EasyFarm.States.FiniteStateMachine.RunStateMachine() in C:\projects\easyfarm\EasyFarm\States\FiniteStateMachine.cs:line 156
   at EasyFarm.States.FiniteStateMachine.<RunFiniteStateMainWithThread>b__9_0() in C:\projects\easyfarm\EasyFarm\States\FiniteStateMachine.cs:line 98
2018-04-06 21:37:44.8868|INFO|LogSink|FSM thread interrupted
System.Threading.ThreadInterruptedException: Thread was interrupted from a waiting state.
   at System.Threading.Thread.SleepInternal(Int32 millisecondsTimeout)
   at System.Threading.Thread.Sleep(Int32 millisecondsTimeout)
   at EasyFarm.States.FiniteStateMachine.RunStateMachine() in C:\projects\easyfarm\EasyFarm\States\FiniteStateMachine.cs:line 159
   at EasyFarm.States.FiniteStateMachine.<RunFiniteStateMainWithThread>b__9_0() in C:\projects\easyfarm\EasyFarm\States\FiniteStateMachine.cs:line 98


Please send help~

**Comment by NotNickerz** [comment]
Anyone able to help?

**Comment by Mykezero** [comment]
Are there any errors in the log file? There could be a easyfarm.log or logfile.txt file that might contain what's happening with the program.
