### ISSUE TITLE
Unable to detect currently running ffxi process

### ISSUE THREAD

**Issue by jormundr8** [EasyFarm/EasyFarm#343]
resolved

**Comment by nubt** [comment]
i get an error after i select my character

2018-05-20 21:08:19.1686 EasyFarm.Logging.NLogTextFileLogger EasyFarm Started ...
2018-05-20 21:08:28.6743 EasyFarm.Logging.NLogTextFileLogger Unhandled Exception
System.DllNotFoundException: Unable to load DLL 'EliteAPI.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at EliteMMO.API.EliteAPI.CreateInstance(Int32 processId)
   at MemoryAPI.Memory.EliteMmoWrapper..ctor(Int32 pid) in C:\projects\easyfarm\MemoryAPI\Memory\EliteMMOWrapper.cs:line 40
   at EasyFarm.Handlers.SelectCharacterRequestHandler.ChangeCharacter(SelectCharacterResult result) in C:\projects\easyfarm\EasyFarm\Handlers\SelectCharacterRequestHandler.cs:line 61
   at EasyFarm.Handlers.SelectCharacterRequestHandler.<Handle>d__2.MoveNext() in C:\projects\easyfarm\EasyFarm\Handlers\SelectCharacterRequestHandler.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EasyFarm.ViewModels.MasterViewModel.<SelectProcess>d__54.MoveNext() in C:\projects\easyfarm\EasyFarm\ViewModels\MasterViewModel.cs:line 251
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EasyFarm.ViewModels.MasterViewModel.<<-ctor>b__8_4>d.MoveNext() in C:\projects\easyfarm\EasyFarm\ViewModels\MasterViewModel.cs:line 79
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__3(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by nubt** [comment]
nevermind, i was missing visual studio stuff. it's working now
