### ISSUE TITLE
FSM Thread cancelled Build 1.0.130

### ISSUE THREAD

**Issue by Voliathon** [EasyFarm/EasyFarm#368]
I'm seeing an FSM thread cancelled issue.
Operating System: Windows 10
All the latest and greatest Windows 10 updates.
All Requirements are installed and the EliteMMO System Checker passes validation.
Please help me out.

EasyFarm starts but it does not start tabbing around for monsters.

`2018-07-01 20:21:30.5982 EasyFarm.Logging.NLogTextFileLogger EasyFarm Started ...
2018-07-01 20:22:23.0060 EasyFarm.Logging.NLogTextFileLogger FSM thread cancelled
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at EasyFarm.States.FiniteStateMachine.RunStateMachine() in C:\projects\easyfarm\EasyFarm\States\FiniteStateMachine.cs:line 139
   at EasyFarm.States.FiniteStateMachine.<RunFiniteStateMainWithThread>b__9_0() in C:\projects\easyfarm\EasyFarm\States\FiniteStateMachine.cs:line 98
2018-07-01 20:22:35.3819 EasyFarm.Logging.NLogTextFileLogger FSM thread cancelled
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at EasyFarm.States.FiniteStateMachine.RunStateMachine() in C:\projects\easyfarm\EasyFarm\States\FiniteStateMachine.cs:line 139
   at EasyFarm.States.FiniteStateMachine.<RunFiniteStateMainWithThread>b__9_0() in C:\projects\easyfarm\EasyFarm\States\FiniteStateMachine.cs:line 98`

**Comment by Voliathon** [comment]
Furthermore when trying to attack a specific mob, I'm seeing this in the same build.

`2018-07-01 21:15:14.2676|INFO|LogSink|FSM thread interrupted
System.Threading.ThreadInterruptedException: Thread was interrupted from a waiting state.
   at System.Threading.Thread.SleepInternal(Int32 millisecondsTimeout)
   at System.Threading.Thread.Sleep(Int32 millisecondsTimeout)
   at MemoryAPI.Memory.EliteMmoWrapper.NavigationTools.MoveForwardTowardsPosition(Func`1 targetPosition, Boolean useObjectAvoidance) in C:\projects\easyfarm\MemoryAPI\Memory\EliteMMOWrapper.cs:line 124
   at MemoryAPI.Memory.EliteMmoWrapper.NavigationTools.GotoNPC(Int32 id, Boolean useObjectAvoidance) in C:\projects\easyfarm\MemoryAPI\Memory\EliteMMOWrapper.cs:line 97
   at EasyFarm.States.ApproachState.Run() in C:\projects\easyfarm\EasyFarm\States\ApproachState.cs:line 66
   at EasyFarm.States.FiniteStateMachine.RunStateMachine() in C:\projects\easyfarm\EasyFarm\States\FiniteStateMachine.cs:line 156
   at EasyFarm.States.FiniteStateMachine.<RunFiniteStateMainWithThread>b__9_0() in C:\projects\easyfarm\EasyFarm\States\FiniteStateMachine.cs:line 98`
