### ISSUE TITLE
geting errors and easy farm stop workin

### ISSUE THREAD

**Issue by mariud** [EasyFarm/EasyFarm#442]
hi this what im geting in logs on winows 10System.InvalidOperationException: Kolekcja zostala zmodyfikowana po utworzeniu wystapienia modulu wyliczajacego.
   w System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   w System.Collections.Generic.Queue`1.Enumerator.MoveNext()
   w System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   w System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   w EasyFarm.States.BattleState.ShouldRecycleBattleStateCheck() w C:\projects\easyfarm\EasyFarm\States\BattleState.cs:wiersz 81
   w EasyFarm.States.BattleState.Run() w C:\projects\easyfarm\EasyFarm\States\BattleState.cs:wiersz 70
   w EasyFarm.States.FiniteStateMachine.RunStateMachine() w C:\projects\easyfarm\EasyFarm\States\FiniteStateMachine.cs:wiersz 171
   w EasyFarm.States.FiniteStateMachine.<RunFiniteStateMainWithThread>b__9_0() w C:\projects\easyfarm\EasyFarm\States\FiniteStateMachine.cs:wiersz 99

**Comment by mariud** [comment]
it works for a bit then it stops plz help

**Comment by kingpin1432** [comment]
I am having similar issues. 





2019-07-14 12:23:47.0260 EasyFarm.Logging.NLogTextFileLogger EasyFarm Started ...
2019-07-14 12:24:00.6141 EasyFarm.Logging.NLogTextFileLogger FSM error
System.NullReferenceException: Object reference not set to an instance of an object.
   at MemoryAPI.Helpers.GetNpcType(EntityEntry entity) in C:\projects\easyfarm\MemoryAPI\Helpers.cs:line 61
   at MemoryAPI.Memory.EliteMmoWrapper.PartyMemberTools.get_NpcType() in C:\projects\easyfarm\MemoryAPI\Memory\EliteMMOWrapper.cs:line 351
   at EasyFarm.States.SummonTrustsState.<>c.<MaxTrustsReached>b__8_1(IPartyMemberTools x) in C:\projects\easyfarm\EasyFarm\States\SummonTrustsState.cs:line 134
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source, Func`2 predicate)
   at EasyFarm.States.SummonTrustsState.MaxTrustsReached(Int32 maxTrustPartySize) in C:\projects\easyfarm\EasyFarm\States\SummonTrustsState.cs:line 132
   at EasyFarm.States.SummonTrustsState.Check() in C:\projects\easyfarm\EasyFarm\States\SummonTrustsState.cs:line 122
   at EasyFarm.States.FiniteStateMachine.RunStateMachine() in C:\projects\easyfarm\EasyFarm\States\FiniteStateMachine.cs:line 161
   at EasyFarm.States.FiniteStateMachine.<RunFiniteStateMainWithThread>b__9_0() in C:\projects\easyfarm\EasyFarm\States\FiniteStateMachine.cs:line 99

**Comment by myrialeen** [comment]
Same problem, it works for some minutes then it stops

**Comment by kingpin1432** [comment]
> Same problem, it works for some minutes then it stops

I actually discovered a work around. At least for my issue. If you have easyfarm summoning trusts, that's when it creates the issues. So just more summon trusts and leave the trust part empty 

Also, I notice that if you had recast times, occasionally if all of the abilities become ready at the same time, ef may crash bc I think it tries to use them all at the same time.

**Comment by myrialeen** [comment]
i summon trust manually and I didn't enable anything about trust re-summon
