### ISSUE TITLE
Keep getting error when I click start

### ISSUE THREAD

**Issue by kingpin1432** [EasyFarm/EasyFarm#449]
2019-07-14 12:23:47.0260 EasyFarm.Logging.NLogTextFileLogger EasyFarm Started ...
2019-07-14 12:24:00.6141 EasyFarm.Logging.NLogTextFileLogger FSM error
System.NullReferenceException: Object reference not set to an instance of an object.
   at MemoryAPI.Helpers.GetNpcType(EntityEntry entity) in C:\projects\easyfarm\MemoryAPI\Helpers.cs:line 61
   at MemoryAPI.Memory.EliteMmoWrapper.PartyMemberTools.get_NpcType() in C:\projects\easyfarm\MemoryAPI\Memory\EliteMMOWrapper.cs:line 351
   at EasyFarm.States.SummonTrustsState.<>c.<MaxTrustsReached>b__8_1(IPartyMemberTools x) in C:\projects\easyfarm\EasyFarm\States\SummonTrustsState.cs:line 134
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source, Func`2 predicate)
   at EasyFarm.States.SummonTrustsState.MaxTrustsReached(Int32 maxTrustPartySize) in C:\projects\easyfarm\EasyFarm\States\SummonTrustsState.cs:line 132
   at EasyFarm.States.SummonTrustsState.Check() in C:\projects\easyfarm\EasyFarm\States\SummonTrustsState.cs:line 122
   at EasyFarm.States.FiniteStateMachine.RunStateMachine() in C:\projects\easyfarm\EasyFarm\States\FiniteStateMachine.cs:line 161
   at EasyFarm.States.FiniteStateMachine.<RunFiniteStateMainWithThread>b__9_0() in C:\projects\easyfarm\EasyFarm\States\FiniteStateMachine.cs:line 99

I tried downloading the newest release, but it doesn't auto fill the trusts, saying the resource is missing so currently I am stuck.

**Comment by raboley** [comment]
You have to copy paste the resources folder from windower/ashita to get autofill to work. Have you unlocked the number of trusts you are trying to summon?
