### ISSUE TITLE
Constant Error and Program Stops every 5-10 minutes

### ISSUE THREAD

**Issue by meekriot** [EasyFarm/EasyFarm#454]
I've been testing it with a small path in Ceizak Battlegrounds. All the settings are pretty much default except I've added in the mob's names. The program stops and gives me an error after 5-10 minutes running. I can't seem to pinpoint what it is, but here is the error log. Any help?

`2019-09-30 20:35:18.9511 EasyFarm.Logging.NLogTextFileLogger EasyFarm Started ...
2019-09-30 20:46:39.2256 EasyFarm.Logging.NLogTextFileLogger FSM error
System.InvalidOperationException: Collection was modified after the enumerator was instantiated.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Queue`1.Enumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at EasyFarm.States.BattleState.ShouldRecycleBattleStateCheck(IGameContext context) in C:\Users\Micah\Desktop\EasyFarm-master\EasyFarm\States\BattleState.cs:line 80
   at EasyFarm.States.BattleState.Run(IGameContext context) in C:\Users\Micah\Desktop\EasyFarm-master\EasyFarm\States\BattleState.cs:line 69
   at EasyFarm.States.FiniteStateMachine.RunStateMachine() in C:\Users\Micah\Desktop\EasyFarm-master\EasyFarm\States\FiniteStateMachine.cs:line 157
   at EasyFarm.States.FiniteStateMachine.<RunFiniteStateMainWithThread>b__10_0() in C:\Users\Micah\Desktop\EasyFarm-master\EasyFarm\States\FiniteStateMachine.cs:line 99`

**Comment by rjtrenchard** [comment]
I was also having this issue, I commented out the contents of "ShouldRecycleBattleStateCheck" located in States/BattleState.cs and rebuilt it, which seems to be a temporary fix.
