### ISSUE TITLE
Is hard to hook to a character, but will eventually.  Runs routes but will not engage anything

### ISSUE THREAD

**Issue by Bairrionn** [EasyFarm/EasyFarm#523]
Hello, So about 8 days ago I must have done something and EasyFarm no longer works.  It does not seem to find resources even though it lets me set the character. When you hit start, the program says its running, but the character does nothing.
 If you try to set a route its always x0 z0.  Stuff like that.  This is the log.  

2022-10-18 06:51:59.6170 EasyFarm.Logging.NLogTextFileLogger EasyFarm Started ...
2022-10-18 06:59:03.3867 EasyFarm.Logging.NLogTextFileLogger FSM thread interrupted
System.Threading.ThreadInterruptedException: Thread was interrupted from a waiting state.
   at System.Threading.Thread.SleepInternal(Int32 millisecondsTimeout)
   at System.Threading.Thread.Sleep(Int32 millisecondsTimeout)
   at EasyFarm.States.ZoneState.<>c.<.ctor>b__1_0() in C:\projects\easyfarm\EasyFarm\States\ZoneState.cs:line 34
   at EasyFarm.States.ZoneState.Run() in C:\projects\easyfarm\EasyFarm\States\ZoneState.cs:line 55
   at EasyFarm.States.FiniteStateMachine.RunStateMachine() in C:\projects\easyfarm\EasyFarm\States\FiniteStateMachine.cs:line 171
   at EasyFarm.States.FiniteStateMachine.<RunFiniteStateMainWithThread>b__9_0() in C:\projects\easyfarm\EasyFarm\States\FiniteStateMachine.cs:line 99

If you keep at it, pressing reset character in the routes thing it will eventually link to the character.  I am able to set a route, which it will then follow but it seems to ignore everything else and wont fight anything

I assume its something dumb and easy, but it eludes me.  Any help would be greatly appreciated. Thank you

**Comment by BananaHammock21** [comment]
I am currently having a similar issue.  I run Windower as admin, have all the prereq programs and files.  

I have tried starting Windower first <as admin and not as admin> and then easy farm as admin and not as admin> and tried to run easy farm before starting Windower.  When I select character it says "Bot loaded:" in the bottom but never hooks my character.  

I cannot get it to do routes and keep getting the message that it cannot find resources for all of the weapon skills, spells, items, and trusts.  The routes always show as X0 Z0 and when i reset character on routes, it will not display anything in box for the routes.

Currently running all updates for Windows 10 and Defender.  I have disabled my antivirus before downloading and before trying to run all programs involved.  Any help on this would be great.

**Comment by JGCaban** [comment]
There is a current known issue with a recent Windows update that appeared to have broken connectivity to the EliteAPI. I had the exact same problem. These are the Windows updates that are known to cause problems:

- KB5018410   <--was causing my issues on Win10
- KB5018418 
- KB5018419 

Simply look for the above updates and uninstall them. Also recommend pausing updates. EasyFarm should have no issues with the API/resources after that. 

Source: http://www.elitemmonetwork.com/forums/viewtopic.php?f=2&t=1427

**Comment by BananaHammock21** [comment]
ty for the reply   will do this when i get back in front of the PC

**Comment by Bairrionn** [comment]
Thank you very much, this worked.

**Comment by BananaHammock21** [comment]
Just got home to make the changes and this worked.  thanks for the speedy reply and assist with fixing it.

**Comment by Lokie925** [comment]
is there anyway that someone can post previous versions of those files i no longer have them in my pc and cant rollback....

**Comment by murphyk0620** [comment]
So I was having the problem today when I attempted it. The only way I could find to attempt an update was to download the current release. Where do I go to install the most updated version to work as expected?
