### ISSUE TITLE
Error when selecting character

### ISSUE THREAD

**Issue by gnarlykoala** [EasyFarm/EasyFarm#524]
Get the message "Unable to load DLL'EliteAPI.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E

Here is the Log from it:

2022-11-05 21:25:47.6332 EasyFarm.Logging.NLogTextFileLogger EasyFarm Started ...
2022-11-05 21:25:58.7440 EasyFarm.Logging.NLogTextFileLogger Unhandled Exception
System.DllNotFoundException: Unable to load DLL 'EliteAPI.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at EliteMMO.API.EliteAPI.CreateInstance(Int32 processId)
   at MemoryAPI.Memory.EliteMmoWrapper..ctor(Int32 pid) in C:\projects\easyfarm\MemoryAPI\Memory\EliteMMOWrapper.cs:line 41
   at EasyFarm.Handlers.SelectCharacterRequestHandler.ChangeCharacter(SelectCharacterResult result) in C:\projects\easyfarm\EasyFarm\Handlers\SelectCharacterRequestHandler.cs:line 61
   at EasyFarm.Handlers.SelectCharacterRequestHandler.<Handle>d__2.MoveNext() in C:\projects\easyfarm\EasyFarm\Handlers\SelectCharacterRequestHandler.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EasyFarm.ViewModels.MasterViewModel.<SelectProcess>d__54.MoveNext() in C:\projects\easyfarm\EasyFarm\ViewModels\MasterViewModel.cs:line 252
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EasyFarm.ViewModels.MasterViewModel.<<-ctor>b__8_4>d.MoveNext() in C:\projects\easyfarm\EasyFarm\ViewModels\MasterViewModel.cs:line 79
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

It also asks when I first open it up if i want to update EliteAPI.dll if tried just clicking cancel as well as pressing ok to update it. Either way ends up the same.

**Comment by Waninoko420** [comment]
I am having this problem now. It will not allow me to load my Character
